// Inicializamos el mazo si no existe, luego añadimos las preguntas
window.misPreguntas = window.misPreguntas || [];
window.misPreguntas.push(
    {   q: "1. ¿Qué estructura no es estudiada por la anatomía macroscópica?:", 
        q1: ["A) corazón"], 
        q2: ["B) pulmones"],
        q3: ["C) linfa"],
        q4: ["D) hipófisis"],
        q5: ["E) glándulas suprarrenales"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "2. ¿Cuál de las siguientes alternativas no corresponden al nivel químico?:", 
        q1: ["A) proteínas"], 
        q2: ["B) carbohidratos"],
        q3: ["C) lípidos"],
        q4: ["D) vitaminas"],
        q5: ["E) fotones"],
        a: "E", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "3. Con respecto a la posición anatómica, ¿cuál de las siguientes alternativas no corresponde?:", 
        q1: ["A) Cuerpo erguido"], 
        q2: ["B) Mirada hacia adelante"],
        q3: ["C) Miembros superiores extendidos"],
        q4: ["D) Palma de las manos hacia abajo"],
        q5: ["E) Punta de los pies hacia adelante"],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "4. ¿Cuál de los siguientes huesos está en posición proximal al húmero?:", 
        q1: ["A) Huesos del carpo"], 
        q2: ["B) Metacarpianos"],
        q3: ["C) Clavícula"],
        q4: ["D) Falange proximal"],
        q5: ["E) Falange distal"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "5. ¿Qué plano divide al cerebro en hemisferios derecho e izquierdo?:", 
        q1: ["A) Plano transversal"], 
        q2: ["B) Plano coronal"],
        q3: ["C) Plano sagital"],
        q4: ["D) Plano parasagital"],
        q5: ["E) Plano horizontal"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "6. ¿Cuál de los siguientes sistemas regulan principalmente la homeostasis?:", 
        q1: ["A) Digestivo y urinario"], 
        q2: ["B) Endocrino urinario"],
        q3: ["C) Nervioso y endocrino"],
        q4: ["D) Respiratorio y urinario"],
        q5: ["E) Digestivo y respiratorio"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "7. ¿Cuál de los siguientes electrolitos se encuentra en menor concentración en el líquido extracelular en comparación al intracelular:", 
        q1: ["A) Na^+"], 
        q2: ["B) Cl^-"],
        q3: ["C) K^+"],
        q4: ["D) Ca^{++}"],
        q5: ["E) HCO_3^-"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "8. El agua representa aproximadamente el 60% del peso corporal ¿En cual de los siguientes espacios se encuentra en mayor proporción:", 
        q1: ["A) Espacio extracelular"], 
        q2: ["B) Espacio tisular"],
        q3: ["C) Espacio intravascular"],
        q4: ["D) Espacio intersticial"],
        q5: ["E) Espacio intracelular"],
        a: "E", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "9. La homeostasia puede ser alterada por pérdida de líquidos que supera los 2500 ml/día lo cual conlleva a deshidratación ¿Cuál de las siguientes alternativas, no es considerada como causa de deshidratación?:", 
        q1: ["A) Hemorragia profusa"], 
        q2: ["B) Quemadura"],
        q3: ["C) Diarreas"],
        q4: ["D) Fractura"],
        q5: ["E) Diabetes insípida"],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },
    
    { q: "10. Si una persona pesa 70 kilogramos. Calcular la cantidad total de agua en su medio interno.:", 
        q1: ["A) 10 litros"], 
        q2: ["B) 12 litros"],
        q3: ["C) 14 litros"],
        q4: ["D) 16 litros"],
        q5: ["E) 18 litros"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" }

);
