// Inicializamos el mazo si no existe, luego añadimos las preguntas
window.misPreguntas = window.misPreguntas || [];
window.misPreguntas.push(
    {   q: "Geometría", 
        a: "A", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/1.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "B", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/2.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "E", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/3.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/4.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/5.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "E", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/6.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/7.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/8.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "E", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/9.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },
    
    { q: "Geometría", 
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/10.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "A", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/11.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/12.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/13.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "C", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/14.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "Geometría", 
        a: "A", 
        inc: ["A", "B", "C", "D", "E"],
        img: "https://raw.githubusercontent.com/hniltonhemenih/geometria/main/15.png", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" }

);
