// Inicializamos el mazo si no existe, luego añadimos las preguntas
window.misPreguntas = window.misPreguntas || [];
window.misPreguntas.push(
    {   q: "1. Se le considera el iniciador de la Zoología por sus numerosos estudios sobre animales y haber establecido la escala natural.", 
        q1: ["A) Platón"], 
        q2: ["B) Teofrasto de Ereso"],
        q3: ["C) Demócrito de Abdera"],
        q4: ["D) Aristóteles de Frigia"],
        q5: ["E) Pitágoras"],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "2. Fue el primero en observar y describir las bacterias, protozoarios y espermatozoides, postulando la teoría animalculista.", 
        q1: ["A) Malpighi"], 
        q2: ["B) Hooke"],
        q3: ["C) Leeuwenhoek"],
        q4: ["D) Pasteur"],
        q5: ["E) Spallanzani"],
        a: "C", 
        inc: ["A", "B", "C", "D", "E"], 
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "3. Una de las clasificaciones más antiguas de las plantas fue hecha por un naturalista griego que estableció la clasificación en Criptógamas y Fanerógamas.", 
        q1: ["A) Teofrasto"], 
        q2: ["B) Parménides"],
        q3: ["C) Epicuro"],
        q4: ["D) Fania"],
        q5: ["E) Thales"],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "4. Se le considera uno de los iniciadores de la práctica médica por sus trabajos en la disección de animales.", 
        q1: ["A) Claudio Galeno"], 
        q2: ["B) Aristóteles"],
        q3: ["C) Ptolomeo"],
        q4: ["D) Hipócrates"],
        q5: ["E) Herófilo"],
        a: "A", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "5. Planteó la Nomenclatura binomial para los seres vivos.", 
        q1: ["A) George Louis Leclerc, Conde de Buffon"], 
        q2: ["B) Charles Lyell"],
        q3: ["C) Alfred Russell Wallace"],
        q4: ["D) Ernst Haeckel"],
        q5: ["E) Carl von Linné"],
        a: "E", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "6. La invención del microscopio compuesto trajo consigo la", 
        q1: ["A) Teoría Atómica."], 
        q2: ["B) Teoría Celular."],
        q3: ["C) Teoría Evolutiva."],
        q4: ["D) Teoría de la Panspermia."],
        q5: ["E) Teoría de la Generación Espontánea."],
        a: "B", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "7. Plantearon la Teoría celular.", 
        q1: ["A) Darwin y Oparin"], 
        q2: ["B) Schleiden y Schwann"],
        q3: ["C) Linné y Ray"],
        q4: ["D) Watson y Crick"],
        q5: ["E) Mendel y De Vries"],
        a: "B", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "8. El inicio del siglo XX, en el campo de la Biología, tiene como principal aporte la", 
        q1: ["A) Teoría Celular."], 
        q2: ["B) Teoría de la Biogénesis."],
        q3: ["C) Teoría Evolutiva."],
        q4: ["D) Genética."],
        q5: ["E) Generación Espontánea."],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },

    { q: "9. El final de la concepción de la generación espontánea se produce como consecuencia de", 
        q1: ["A) la visión dialéctica de la naturaleza."], 
        q2: ["B) el desarrollo del método de experimentación."],
        q3: ["C) el planteamiento de la evolución biológica."],
        q4: ["D) la construcción de microscopios."],
        q5: ["E) la propuesta de la Teoría celular."],
        a: "B", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" },
    
    { q: "10. Propusieron el modelo de la doble hélice para explicar la estructura del ADN.", 
        q1: ["A) Darwin y Oparin"], 
        q2: ["B) Schleiden y Schwann"],
        q3: ["C) Linné y Ray"],
        q4: ["D) Watson y Crick"],
        q5: ["E) Mendel y De Vries"],
        a: "D", 
        inc: ["A", "B", "C", "D", "E"],
        img: "", 
        devText: "Desarrollo no disponible.", 
        devImg: "", 
        youtubeId: "" }

);
